kind: Pod
apiVersion: v1
metadata:
  name: labelpodqa
  labels:                                                   
    env: qa
    class: pods
    department: IT
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Learning Labels & Selector; sleep 5 ; done"]